//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public int AlbumId { get; set; }
        public string AlbumName { get; set; }
        public string Genre { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int SongAmount { get; set; }
        public string ArtistName { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
