//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concerts
    {
        public int ConcertID { get; set; }
        public string NameOfArtist { get; set; }
        public System.DateTime ConcertDate { get; set; }
        public string ConcertPlace { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
