//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMembers
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string GroupOfMemberName { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
