//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int SongId { get; set; }
        public string SongName { get; set; }
        public string SongLyrics { get; set; }
        public string ArtistName { get; set; }
    
        public virtual Artists Artists { get; set; }
    }
}
